site_name: ryvencore-qt

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand

nav:
  - Welcome: index.md
  - Getting Started: getting_started.md
  - Features: features.md
  - GUI: gui.md
  - Threading: threading.md
  - API Reference: api.md

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - toc:
      toc_depth: 3

extra_css:
  - extra_style_sheet.css